services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mareo_envios_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d

  mareo-envios:
    build:
      context: ./mareo-envios
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      PORT: 8081
      app.task-processor.url: http://task-processor:8082

  task-processor:
    build:
      context: ./task-processor
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    environment:
      PORT: 8082
      app.mareoenvios.url: http://mareo-envios:8081
      
volumes:
  postgres_data: