services:
  postgres:
      image: postgres:latest
      ports:
        - "8083:5432"
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=mareo_envios_db
      volumes:
        - postgres_data:/var/lib/postgresql/data
        - ./sql:/docker-entrypoint-initdb.d
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 5s
        retries: 5
        start_period: 10s

volumes:
   postgres_data: